export const SET_EMAIL = 'set_email'
export const SET_CODE = 'set_code'
export const SET_NAME = 'set_name'
export const SET_DOB = 'set_dob'
export const EMPLOYEE_SET_AMOUNT = 'employee_set_amount'
export const RESET_VALUES = 'reset_values'