export const EDIT_USERCODE = 'edit_usercode'
export const EDIT_USERNAME = 'edit_username'
export const EDIT_USERDOB = 'edit_userdob'
export const EDIT_USEREMAIL = 'edit_useremail'
export const EDIT_USERAMOUNT = 'edit_useramount'
export const USER_STORE_INITIAL_DATA = 'user_store_initial_data'